name: Extract zip files

on:
  push:
    paths:
      - 'esekoir_github.zip'  # اسم ملف zip الذي رفعته

jobs:
  unzip-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # مهم للسماح بالـ push

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Unzip the file
        run: |
          rm -rf extracted
          mkdir extracted
          unzip esekoir_github.zip -d extracted
          cp -r extracted/* ./

      - name: Commit extracted files
        run: |
          git config --local user.email "together20032308@gmail.com"
          git config --local user.name "esekoir"
          git add .
          git commit -m "Extracted esekoir_github.zip" || echo "No changes to commit"
          git push
